//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDb) DeepCopyInto(out *MongoDb) {
	*out = *in
	out.DBSize = in.DBSize.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDb.
func (in *MongoDb) DeepCopy() *MongoDb {
	if in == nil {
		return nil
	}
	out := new(MongoDb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NginxIngress) DeepCopyInto(out *NginxIngress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NginxIngress.
func (in *NginxIngress) DeepCopy() *NginxIngress {
	if in == nil {
		return nil
	}
	out := new(NginxIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotesApp) DeepCopyInto(out *NotesApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotesApp.
func (in *NotesApp) DeepCopy() *NotesApp {
	if in == nil {
		return nil
	}
	out := new(NotesApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotesApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotesAppBe) DeepCopyInto(out *NotesAppBe) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotesAppBe.
func (in *NotesAppBe) DeepCopy() *NotesAppBe {
	if in == nil {
		return nil
	}
	out := new(NotesAppBe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotesAppFe) DeepCopyInto(out *NotesAppFe) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotesAppFe.
func (in *NotesAppFe) DeepCopy() *NotesAppFe {
	if in == nil {
		return nil
	}
	out := new(NotesAppFe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotesAppList) DeepCopyInto(out *NotesAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NotesApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotesAppList.
func (in *NotesAppList) DeepCopy() *NotesAppList {
	if in == nil {
		return nil
	}
	out := new(NotesAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NotesAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotesAppSpec) DeepCopyInto(out *NotesAppSpec) {
	*out = *in
	out.NotesAppFe = in.NotesAppFe
	out.NotesAppBe = in.NotesAppBe
	in.MongoDb.DeepCopyInto(&out.MongoDb)
	out.NginxIngress = in.NginxIngress
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotesAppSpec.
func (in *NotesAppSpec) DeepCopy() *NotesAppSpec {
	if in == nil {
		return nil
	}
	out := new(NotesAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotesAppStatus) DeepCopyInto(out *NotesAppStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotesAppStatus.
func (in *NotesAppStatus) DeepCopy() *NotesAppStatus {
	if in == nil {
		return nil
	}
	out := new(NotesAppStatus)
	in.DeepCopyInto(out)
	return out
}
